# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d07d9eeaf373be4c6d4062c822e635aa83a2295bae72072be5371a70f502d47c64f301f1862f40db5e481f12fcc22fb3c634c661a2fcde0f0e0e427a6403d243

test:
  secret_key_base: 03cab6df46f24ab98b67f183a1dd52a77b7b58801b6a70d071d293b49d0e788ebf52a6d6f743770cc417d72ad8ad3345697d16ca16e57d81340de1acaadfa53c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
